dir_path: "E:/LLMS/Fine-tuning/"
dir_output: "E:/LLMS/Fine-tuning/output"
csv_file_path: "E:/LLMS/Fine-tuning/output/csvfile.csv"
model_name_path: "gpt2"
model_parameters_print: true
max_seq_length: 512
chars_per_token: 3.5
fim_rate: 0.15
fim_spm_rate: 0.2
seed: 10
model_output_dir: "./Hemanth_LLMs1"
num_train_epochs: 2
save_total_limit: 5
per_device_train_batch_size: 1
warmup_steps: 1
weight_decay: 0.1
dataloader_drop_last: true
bf16: true
logging_steps: 1
learning_rate: 0.1
gradient_checkpointing: false
push_to_hub: true
remove_unused_columns: true
max_steps: 10
