dir_path: "E:/LLMS/hemanth/"
dir_output: "E:/LLMS/hemanth/output/"
csv_file_path: "E:/LLMS/hemanth/csvfile.csv"
model_name_path: "gpt2"
model_parameters_print: true
max_seq_length: 100
chars_per_token: 3.5
fim_rate: 0.15
fim_spm_rate: 0.2
seed: 10
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
learning_rate: 5e-5
weight_decay: 0.0
num_train_epochs: 2
max_train_steps: 1
gradient_accumulation_steps: 1
lr_scheduler_type: "linear"
num_warmup_steps: 0
output_dir: "model-gpt2-test"
push_to_hub: false
hub_model_id: "gpt2"
hub_token: "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"
trust_remote_code: false
checkpointing_steps: "E:/LLMS/hemanth/output/output"
resume_from_checkpoint: null
with_tracking: true
report_to: "all"
ignore_mismatched_sizes: false