dataset_name: "fka/awesome-chatgpt-prompts"
dataset_config_name: null
train_file: null
validation_file: null
validation_split_percentage: 5
model_name_or_path: "gpt2"
config_name: null
tokenizer_name: "gpt2"
use_slow_tokenizer: false
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
learning_rate: 5.0e-05
weight_decay: 0.0
num_train_epochs: 3
max_train_steps: null
gradient_accumulation_steps: 1
lr_scheduler_type: linear
num_warmup_steps: 0
output_dir: "./output"
seed: 20
model_type: null
block_size: null
preprocessing_num_workers: null
overwrite_cache: true
no_keep_linebreaks: false
push_to_hub: true
hub_model_id: null
hub_token: "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"
trust_remote_code: true
checkpointing_steps: null
resume_from_checkpoint: null
with_tracking: false
report_to: all
low_cpu_mem_usage: false