dir_path: "E:/LLMS/hemanth/fine_tuning/Fine_tuning_LLMS/Hemanth/Hemanth_LLMs/model_loder/pre_training/"
dir_output: "E:/LLMS/hemanth/fine_tuning/Fine_tuning_LLMS/Hemanth/Hemanth_LLMs/model_loder/output/"
csv_file_path: "E:/LLMS/hemanth/fine_tuning/Fine_tuning_LLMS/Hemanth/Hemanth_LLMs/model_loder/csvfile.csv"
model_name_path: "gpt2"
model_parameters_print: false
max_seq_length: 1024
chars_per_token: 3.5
fim_rate: 0.15
fim_spm_rate: 0.2
seed: 10
model_output_dir: "./Hemanth_LLMs"
num_train_epochs: 250
save_total_limit: 5
per_device_train_batch_size: 1
warmup_steps: 100
weight_decay: 0.01
dataloader_drop_last: true
bf16: true
logging_steps: 100
learning_rate: 0.001
gradient_checkpointing: false
push_to_hub: true
remove_unused_columns: true
max_steps: 10000
