dataset_name_or_path: 'fka/awesome-chatgpt-prompts'
config: ''
dataset_config_name: null
train_file: null
validation_file: null
validation_split_percentage: 5
model_name_or_path: 'gpt2'
config_name: null
tokenizer_name_or_path: 'gpt2'
use_slow_tokenizer: false
per_device_train_batch_size: 8
per_device_eval_batch_size: 8
learning_rate: 5e-5
weight_decay: 0.0
num_train_epochs: 3
max_train_steps: null
gradient_accumulation_steps: 1
lr_scheduler_type: linear
num_warmup_steps: 0
output_dir: null
seed: null
ignore_pad_token_for_loss: true
max_length: 512
max_target_length: 128
pad_to_max_length: false
preprocessing_num_workers: null
overwrite_cache: false
no_keep_linebreaks: false
push_to_hub: false
hub_model_id: null
hub_token: null
trust_remote_code: false
checkpointing_steps: null
resume_from_checkpoint: null
with_tracking: false
report_to: tensorboard
low_cpu_mem_usage: false
temperature: 0.8
k: 40
p: 0.95
adapter_name_or_path: null
